### ISSUE TITLE
IE图片无法加载，报“DOM7009 unable to decode image at url“警告

### ISSUE THREAD

**Issue by naseeihity** [naseeihity/LearnReact#34]
背景：IE 浏览器，单页面应用，单个 tab 页签，加载大量图片时出现图片无法显示的问题（显示为左上角为小叉），在新的 tab 页签直接访问图片的 url却能显示。

对于 DOM7009 网络上多为以下几种原因：
1.  图片后缀名不正确，比如 png 的图片在 src 中写成了jpg 格式
2. 图片颜色编码问题，IE浏览器不识别CMYK模式的图
3. 配置文件中，`<add name="X-Content-Type-Options" value="nosniff" />`会阻止浏览器在请求的资源格式与预先设定的图片格式不匹配时自动调整。所以当图片请求的`content-type`设置为`image/png`时，当请求的图片时 jpg 时就无法加载了。
4. 单张图片过大，会导致浏览器无法加载（推测与浏览器内存或缓存相关）

以上几种情况都未能解决我的问题，我面对的现象为对于较大的图片(10mb)左右，加载20张左右就会不能加载，对于较小的图片，每页100张，大概能加载不到3页的样子。考虑为 ie 内存机制的问题，通过百度图片(其为不断地懒加载)搜索测试，在加载20mb 图片(很多张小图)后也会出现这种现象。

推测 IE 的内存机制对单tab 页签的内存使用有限制，但考虑页面中的翻页不应导致内存不断增加，推测存在内存泄漏。

**解决**：排查后发现果然存在大量内存泄漏，一个 jquery 的 lazyload 小插件中存在内存泄漏。

**仍旧存在的问题**：当图片很大时，甚至一页图片(100张)也不能全部正常显示，所以需要在图片传递到前端之前做好压缩工作。

我们在制作弹框模块时往往有一个蒙版，来阻止用户在弹框时点击页面其他地方，一般会这样实现：
```css
.model{
position: fixed;
left: 0;
top: 0;
right: 0;
bottom: 0;
z-index: 999;
}
```

但是 IE 的表现却出乎我们的意料，这种样式下，页面中的相关链接或者绑定了事件的按钮依然可以点击触发，我们需要给遮罩层加上颜色才能使得他的表现和 Chrome 统一

```css
.model{
position: fixed;
left: 0;
top: 0;
right: 0;
bottom: 0;
z-index: 999;
/* for ie*/
background-color: rgba(0,0,0,0);
}
```

**Comment by naseeihity** [comment]
我们在制作弹框模块时往往有一个蒙版，来阻止用户在弹框时点击页面其他地方，一般会这样实现：
```css
.model{
position: fixed;
left: 0;
top: 0;
right: 0;
bottom: 0;
z-index: 999;
```

但是 IE 的表现却出乎我们的意料，这种样式下，页面中的相关链接或者绑定了事件的按钮依然可以点击触发，我们需要给遮罩层加上颜色才能使得他的表现和 Chrome 统一

```css
.model{
position: fixed;
left: 0;
top: 0;
right: 0;
bottom: 0;
z-index: 999;
/* for ie*/
background-color: rgba(0,0,0,0);
}
```
