### ISSUE TITLE
再看垂直居中

### ISSUE THREAD

**Issue by naseeihity** [naseeihity/LearnReact#39]
之前总结过[水平垂直居中的方法](https://github.com/naseeihity/LearnToLearn/blob/master/Notes/CSS/%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD%E7%9A%84%E5%87%A0%E7%A7%8D%E6%96%B9%E6%B3%95.md),
以及[CSS-tricks](https://css-tricks.com/centering-css-complete-guide/)中也有清晰的总结。

最近发现项目中其他人写的样式中大量使用了`display:table-cell`去实现水平垂直居中.

```css
.father{
  display: table-cell;
  width: 500px;
  height: 300px;
  background-color: #de3;
  vertical-align: middle;
  text-align: center;
}

.child{
  display: inline-block;
  max-width:400px;
  max-height:200px;
  background-color: #fd2;
}
```
优势在于不会有position：absolute的负面影响

以及实现多行元素垂直居中：
```css
.father{
  display: table-cell;
  width: 100px;
  height: 200px;//高度设置无效
  background-color: #de3;
  vertical-align: middle;
  text-align: center;
  word-break: normal;
}
```
这一方法的问题在于：
- 高度设置无效
- overflow设置无效
- margin不感知
- 与 position/float等存在冲突

多行文字垂直居中：
```css
.flex-center-vertically {
  display: flex;
  justify-content: center;
  flex-direction: column;
  height: 400px;
}

.ghost-center {
  position: relative;
}
.ghost-center::before {
  content: " ";
  display: inline-block;
  height: 100%;
  width: 1%;
  vertical-align: middle;
}
.ghost-center p {
  display: inline-block;
  vertical-align: middle;
}
```
