### ISSUE TITLE
SCSS与POSTCSS

### ISSUE THREAD

**Issue by naseeihity** [naseeihity/LearnReact#51]
# SCSS
## 变量

```scss
$font-stack:    Helvetica, sans-serif;
$primary-color: #333;

body {
  font: 100% $font-stack;
  color: $primary-color;
}
```

## 嵌套

```scss
nav {
  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  li { display: inline-block; }

  a {
    display: block;
    padding: 6px 12px;
    text-decoration: none;
  }
}
```

## 导入局部公共片段
```
// _reset.scss
@import 'reset';
``` 

## 混入
```scss
@mixin border-radius($radius) {
  -webkit-border-radius: $radius;
     -moz-border-radius: $radius;
      -ms-border-radius: $radius;
          border-radius: $radius;
}

.box { @include border-radius(10px); }
```

## 扩展和继承
```scss
// This CSS won't print because %equal-heights is never extended.
%equal-heights {
  display: flex;
  flex-wrap: wrap;
}

// This CSS will print because %message-shared is extended.
%message-shared {
  border: 1px solid #ccc;
  padding: 10px;
  color: #333;
}

.message {
  @extend %message-shared;
}

.success {
  @extend %message-shared;
  border-color: green;
}

.error {
  @extend %message-shared;
  border-color: red;
}

.warning {
  @extend %message-shared;
  border-color: yellow;
}
```

## 运算
```scss
.container { width: 100%; }


article[role="main"] {
  float: left;
  width: 600px / 960px * 100%;
}

aside[role="complementary"] {
  float: right;
  width: 300px / 960px * 100%;
}
```

# POSTCSS
他不是一个CSS预处理器，他通过诸多插件的支持，可以实现预处理，后处理，使用未来的语法，优化等功能，灵活可配，可自己编写插件。

## 常用插件
- cssnext 使用一些css的新特性
- mqpacker 优化媒体查询
- cssnano 压缩
- postcss-reporter 日志

## 使用

```
1. 安装相关的依赖
2. webpack配置

module.exports = {
    module: {
        rules: [
            {
                test: /\.css$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'style-loader',
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            importLoaders: 1,
                        }
                    },
                    {
                        loader: 'postcss-loader'
                    }
                ]
            }
        ]
    }
}

3. postcss配置

module.exports = {
    plugins: [
        require('precss'),
        require('autoprefixer')
    ]
}
```
